# This is a basic workflow to help you get started with Actions
name: CI/CD Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  front:
    name: Frontend CI/CD
    runs-on: ec2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # - name: Set up node
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: "20.x"

      - name: docker Down
        run: docker compose down

      - name: docker remove image
        run: docker rmi nmm_frontend
        continue-on-error: true

      - name: docker up
        run: docker compose up -d --build

      - name: remove .env file
        run: rm .env
        continue-on-error: true
